spring.application.name=KairoLink
server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true
spring.flyway.placeholders.booking_column_storage=STORED

spring.thymeleaf.cache=false

spring.devtools.restart.enabled=true

kairolink.osrm.base-url=${OSRM_BASE_URL:https://router.project-osrm.org}
kairolink.nominatim.base-url=${NOMINATIM_BASE_URL:https://nominatim.openstreetmap.org}
kairolink.nominatim.user-agent=${NOMINATIM_USER_AGENT:KairoLink/0.0.1}