CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    driver_id BIGINT NOT NULL,
    model VARCHAR(100) NOT NULL,
    number_plate VARCHAR(30) NOT NULL,
    seats INTEGER NOT NULL,
    photo_reference VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_vehicles PRIMARY KEY (id),
    CONSTRAINT uk_vehicles_driver UNIQUE (driver_id),
    CONSTRAINT fk_vehicles_driver
        FOREIGN KEY (driver_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_vehicles_seats_positive CHECK (seats > 0)
);
