CREATE TABLE rides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    driver_id BIGINT NOT NULL,
    source VARCHAR(150) NOT NULL,
    destination VARCHAR(150) NOT NULL,
    departure_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    seats INTEGER NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_rides PRIMARY KEY (id),
    CONSTRAINT fk_rides_driver
        FOREIGN KEY (driver_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_rides_seats_positive CHECK (seats > 0),
    CONSTRAINT ck_rides_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_rides_status
        CHECK (status IN ('CREATED', 'ACTIVE', 'ONGOING', 'COMPLETED', 'CANCELLED'))
);
