CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rider_id BIGINT NOT NULL,
    ride_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    seats_requested INTEGER NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    active_booking_key BOOLEAN GENERATED ALWAYS AS (
        CASE WHEN status IN ('PENDING', 'CONFIRMED') THEN TRUE ELSE NULL END
    ),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_rider
        FOREIGN KEY (rider_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_bookings_ride
        FOREIGN KEY (ride_id)
        REFERENCES rides (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_bookings_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_bookings_seats_requested_positive
        CHECK (seats_requested > 0),
    CONSTRAINT ck_bookings_total_price_non_negative
        CHECK (total_price >= 0)
);

CREATE INDEX idx_bookings_rider_created_at
    ON bookings (rider_id, created_at DESC);

CREATE INDEX idx_bookings_ride
    ON bookings (ride_id);

CREATE INDEX idx_bookings_status
    ON bookings (status);

CREATE UNIQUE INDEX uk_bookings_active_rider_ride
    ON bookings (rider_id, ride_id, active_booking_key);
