CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ride_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    reviewed_user_id BIGINT NOT NULL,
    stars INTEGER NOT NULL,
    comment VARCHAR(500),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_ratings PRIMARY KEY (id),
    CONSTRAINT uk_ratings_ride_reviewer_reviewed_user
        UNIQUE (ride_id, reviewer_id, reviewed_user_id),
    CONSTRAINT fk_ratings_ride
        FOREIGN KEY (ride_id)
        REFERENCES rides (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ratings_reviewer
        FOREIGN KEY (reviewer_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ratings_reviewed_user
        FOREIGN KEY (reviewed_user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_ratings_stars
        CHECK (stars >= 1 AND stars <= 5)
);

