CREATE TABLE driver_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ride_id BIGINT NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL,
    longitude NUMERIC(9, 6) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_driver_locations PRIMARY KEY (id),
    CONSTRAINT uq_driver_locations_ride UNIQUE (ride_id),
    CONSTRAINT fk_driver_locations_ride
        FOREIGN KEY (ride_id)
        REFERENCES rides (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_driver_locations_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT ck_driver_locations_longitude CHECK (longitude >= -180 AND longitude <= 180)
);
