CREATE TABLE issue_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reporter_id BIGINT NOT NULL,
    ride_id BIGINT,
    booking_id BIGINT,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_issue_reports PRIMARY KEY (id),
    CONSTRAINT fk_issue_reports_reporter
        FOREIGN KEY (reporter_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_issue_reports_ride
        FOREIGN KEY (ride_id)
        REFERENCES rides (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_issue_reports_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings (id)
        ON DELETE SET NULL,
    CONSTRAINT ck_issue_reports_status
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED'))
);

CREATE INDEX idx_issue_reports_created_at
    ON issue_reports (created_at DESC);

CREATE INDEX idx_issue_reports_status
    ON issue_reports (status);

CREATE INDEX idx_issue_reports_reporter
    ON issue_reports (reporter_id);
