CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rider_id BIGINT NOT NULL,
    ride_id BIGINT NOT NULL,
    active_booking_key BIGINT,
    status VARCHAR(20) NOT NULL,
    requested_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT uk_bookings_active_rider_ride
        UNIQUE (rider_id, ride_id, active_booking_key),
    CONSTRAINT fk_bookings_rider
        FOREIGN KEY (rider_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_bookings_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED'))
);

CREATE INDEX ix_bookings_rider_requested
    ON bookings (rider_id, requested_at DESC);

CREATE INDEX ix_bookings_ride_status
    ON bookings (ride_id, status);
