CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    receiver_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(150) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_receiver
        FOREIGN KEY (receiver_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_notifications_type
        CHECK (type IN (
            'BOOKING_REQUESTED',
            'BOOKING_ACCEPTED',
            'BOOKING_REJECTED',
            'RIDE_CANCELLED',
            'RIDE_REMINDER',
            'GENERAL'
        ))
);
